### ISSUE TITLE
Updating to Laravel 6: Call to undefined method Monolog\Logger::getMonolog()

### ISSUE THREAD

**Issue by johnnywo** [vojtasvoboda/oc-errorlogger-plugin#10]
When trying to update to latest Version of October with Laravel 6 step **composer update**:
(followed steps from: https://shopaholic.one/blog/how-upgrade-october-cms-laravel-6, one difference - my build was already 471 (instead of 469), ist shows now after updating 470)

**In Logger.php line 273:  Call to undefined method Monolog\Logger::getMonolog()**

after manually renaming plugin folder to vojtasvoboda.___errorlogger I was able to do a composer update without error messages.

**Comment by vojtasvoboda** [comment]
Fixed by #13
