### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by LukeTowers** [vojtasvoboda/oc-errorlogger-plugin#6]
Could you add this plugin to Packagist so that we can add it to our projects directly through composer please? Side note with that, please comment on https://github.com/composer/installers/pull/379 so that we can fix support for `october-plugin` composer packages that use the optional `oc-` prefix in their repositories.

**Comment by vojtasvoboda** [comment]
All my plugins are on Packagist since 2016: https://packagist.org/packages/vojtasvoboda/

Error logger plugin: https://packagist.org/packages/vojtasvoboda/oc-errorlogger-plugin
