### ISSUE TITLE
  Class 'VojtaSvoboda\ErrorLogger\SyslogHandler' not found

### ISSUE THREAD

**Issue by bhargavy** [vojtasvoboda/oc-errorlogger-plugin#8]
I'm setting this error. 

Installed on my localhost, Windows 10, php7

    Class 'VojtaSvoboda\ErrorLogger\SyslogHandler' not found

**Comment by vojtasvoboda** [comment]
Version 1.0.7 ready at the Market, you can do an update. Thanks for reporting this issue.
