### ISSUE TITLE
An invalid form control with name ... is not focusable

### ISSUE THREAD

**Issue by kosmonowt** [vojtasvoboda/oc-errorlogger-plugin#9]
Hi there, using current Chromium engine and having a problem that does not let me save the backend settings.
However I am not sure if it's a problem with this plugin or the sentry plugin.

That's my JavaScript Console output:

```
An invalid form control with name='Settings[slack_token]' is not focusable.
An invalid form control with name='Settings[slack_channel]' is not focusable.
An invalid form control with name='Settings[slack_username]' is not focusable.
An invalid form control with name='Settings[syslog_ident]' is not focusable.
An invalid form control with name='Settings[syslog_facility]' is not focusable.
An invalid form control with name='Settings[newrelic_appname]' is not focusable.
```

any Idea how to solve this problem?

I only want to use sentry tracking, but this does not work since it's not possible to save my DSN...

**Comment by vojtasvoboda** [comment]
Hi @kosmonowt, thanks for reporting an issue. I just made a fix in this plugin: https://github.com/vojtasvoboda/oc-errorlogger-plugin/commit/bb38f691abb2d1b49fa3ab1effa2f985df8bd70d

And also made PR to the Sentry plugin: https://github.com/skydiver/october-plugin-sentryerrorlogger/pull/8

Should works (tested on live project).
